# swagger: '2.0'
# openapi: '3.0.1',
# info:
#   description: Node.js Rest API doc
#   version: '1.0.0'
#   title: Node Rest API documentation
#   termsOfService: 'http://swagger.io/terms/'
#   contact:
#     email: rapiddevpro@gmail.com
#   license:
#     name: Apache 2.0
#     url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
#   servers: [
#         {
#             url: 'http://localhost:5000/',
#             description: 'Local server',
#         },
#   ],
#   # basePath: /api/v1
#   schemes:
#   - http
# paths:
#   /getProducts:
#     get:
#       security:
#         - Bearer: []
#       tags:
#         - Product Module
#       summary: Product API
#       description: API for fetching all products
#       produces:
#         - application/json
#       responses:
#         '200':
#           description: Product fetched Successfully
#           schema:
#             $ref: '#/definitions/ApiResponse'
#         '400':
#           description: Invalid Fields
#         '500':
#           description: Internal Server Error
# securityDefinitions:
#   Bearer:
#     type: apiKey
#     name: Authorization
#     in: header
# definitions:
#   User:
#     properties:
#       email:
#         type: string
#         description: email of user
#       password:
#         type: string
#         description: password of the user
#   Product:
#     properties:
#       name:
#         type: string
#         description: product name
#       price:
#         type: number
#         description: product price
#       brand:
#         type: string
#         description: product brand
#   ApiResponse:
#     type: object
#     properties:
#       status:
#         type: integer
#       message:
#         type: string
#       body:
#         type: object
